project_id = "gvcctjmxelxirczyessq"

[functions.analyze-website]
verify_jwt = false

[functions.analyze-business]
verify_jwt = false

[functions.chat-ai]
verify_jwt = false

[functions.process-documents]
verify_jwt = false