// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvcctjmxelxirczyessq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2Y2N0am14ZWx4aXJjenllc3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5MDU2NzQsImV4cCI6MjA1MTQ4MTY3NH0.Ej2gl5A7O8DLnTCWbegYVKrNBBqn5vPLOJLZNjdmj-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});